### ISSUE TITLE
update_fields შეგიძლია ჩაამტო

### ISSUE THREAD

**Issue by MariamKipshidze** [Lasha-Nikolaishvili/Library-Management-System#1]
https://github.com/Lasha-Nikolaishvili/Library-Management-System/blob/1c0bbd896bc432d8c4f97a879e6e09501e437ad4/rest_api/views.py#L62

**Comment by MariamKipshidze** [comment]
https://docs.djangoproject.com/en/5.0/ref/models/instances/#saving-objects

**Comment by Lasha-Nikolaishvili** [comment]
გამარჯობა მარიამ, ჩავამატე.
